### ISSUE TITLE
Reloading services

### ISSUE THREAD

**Issue by martyphee** [jhipster/jhipster-loaded#4]
I have a number of services which I specified the names of them.  It will reload the first time because it thinks it's a new class, but the next time it goes into a loop spitting out the log message below.

In this instance:

``` java
    @Service("TRUE_FALSE_SERVICE")
    public class TrueFalseService
```

```
[INFO] io.github.jhipster.loaded.JHipsterReloaderThread - Batch reload in progress...
[WARN] io.github.jhipster.loaded.reloader.SpringReloader - Could not hot reload Spring bean!
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.ceshop.controlcenter.service.lesson.TrueFalseService] is defined
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:319) ~[spring-beans-4.0.3.RELEASE.jar:4.0.3.RELEASE]
    at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:985) ~[spring-context-4.0.3.RELEASE.jar:4.0.3.RELEASE]
    at io.github.jhipster.loaded.reloader.SpringReloader.start(SpringReloader.java:162) [core-0.4.jar:na]
    at io.github.jhipster.loaded.reloader.SpringReloader.reload(SpringReloader.java:106) [core-0.4.jar:na]
    at io.github.jhipster.loaded.JHipsterReloaderThread.batchReload(JHipsterReloaderThread.java:192) [core-0.4.jar:na]
    at io.github.jhipster.loaded.JHipsterReloaderThread.run(JHipsterReloaderThread.java:139) [core-0.4.jar:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_05]
Disconnected from the target VM, address: '127.0.0.1:59746', transport: 'socket'
```

**Comment by jmirc** [comment]
Sorry for the late answer.
I know spring doesn't allow to start the name of the service with an Uppercase. If you did, the service or the bean will not be called. Can you try to lowercase the first letter like tRUE_FALSE_SERVICE?

**Comment by martyphee** [comment]
Didn't work.  Same issue.

**Comment by martyphee** [comment]
Was 0.7 release supposed to fix this or is it a issue with spring?

I'm still getting the same warnings after upgrading to 0.7.

```
[WARN] io.github.jhipster.loaded.reloader.SpringReloader - Could not hot reload Spring bean!
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.ceshop.controlcenter.service.lesson.StudentPollService] is defined
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:319) ~[spring-beans-4.0.3.RELEASE.jar:4.0.3.RELEASE]
    at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:985) ~[spring-context-4.0.3.RELEASE.jar:4.0.3.RELEASE]
    at io.github.jhipster.loaded.reloader.SpringReloader.start(SpringReloader.java:162) [core-0.7.jar:na]
    at io.github.jhipster.loaded.reloader.SpringReloader.reload(SpringReloader.java:106) [core-0.7.jar:na]
    at io.github.jhipster.loaded.JHipsterReloaderThread.batchReload(JHipsterReloaderThread.java:206) [core-0.7.jar:na]
    at io.github.jhipster.loaded.JHipsterReloaderThread.run(JHipsterReloaderThread.java:153) [core-0.7.jar:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_05]
```
